blank_lines_upper_bound = 2
imports_layout = "HorizontalVertical"
fn_single_line = true
max_width = 160
merge_imports = true
reorder_impl_items = true
report_todo = "Unnumbered"
report_fixme = "Unnumbered"
struct_field_align_threshold = 20
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
