[package]
name = "campaign-manager"
version = "0.1.0"
authors = ["Shaun Taheri <shaun.taheri@here.com>"]
publish = false

[[bin]]
name = "campaign"
path = "src/main.rs"

[dependencies]
clap = "2.31.2"
env_logger = "0.5.10"
failure = "0.1.1"
log = "0.4.2"
reqwest = "0.8.6"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.19"
toml = "0.4.6"
uuid = { version = "0.6.5", features = ["serde"] }

[profile.release]
lto = true