# specify each hardware identifier in square brackets
[some-ecu-type]
target_format = "binary"
generate_diff = true

# optionally match `from` version before updating
[some-ecu-type.from]
name = "somefile"
version = "1.0.1"
length = 1024
hash = "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"
method = "sha256"

# required metadata specifying update target
[some-ecu-type.to]
name = "somefile"
version = "1.0.2"
length = 1025
hash = "abcd012345678901234567890123456789012345678901234567890123456789"
method = "sha256"


# specify a new hardware update with the minimum required fields
# (sets `target_format="ostree"`, `length=0`, `method="sha256"` and `hash` to the value of `version`)
["another ecu type".to]
name = "my-branch"
version = "012345678901234567890123456789012345678901234567890123456789abcd"